service: HttpIntroPhp

provider:
  name: aws
  region: eu-west-2
  runtime: provided

functions:
  hello:
    handler: handler.php
    layers:
      - ${bref:layer.php-74}
    events:
      - httpApi:
          - '*'

plugins:
  - ./vendor/bref/bref
