service: HttpInternalApiGo

provider:
  name: aws
  region: eu-west-2
  runtime: go1.x
  iamRoleStatements:
    - Effect: Allow
      Action: lambda:InvokeFunction
      Resource: 'arn:aws:lambda:eu-west-2:*:function:${self:service}-${self:provider.stage}-internalApi'

functions:
  internalApi:
    handler: bin/internal-api

  externalApi:
    handler: bin/external-api
    events:
      - httpApi:
          path: /
          method: GET
